name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install
      - name: Publish to GitHub Packages
        run: npm publish  --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
